### ISSUE TITLE
Example for EAP 6.3

### ISSUE THREAD

**Issue by tokad** [fcorneli/jberet-eap6#2]
Hello,

thx for your great work.
I tried to test jberet-eap6 on EAP6.3 with a simple batchlet.
At first I downloaded the eap6-batch-dist-1.0.2.zip. I extracted the modules into the modules folder of my EAP. After that I created a Java EE Web Project in Jboss Developer Studio and handeled the dependencies.
My example starts the job with @Schedule. After starting I get the following error message:

Caused by: javax.batch.operations.BatchRuntimeException: JBERET000640: A BatchEnvironment implementation could not be found. Please ensure the SPI has been implemented and is on the class path
    at org.jberet.operations.JobOperatorImpl.<init>(JobOperatorImpl.java:86)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_60]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [rt.jar:1.7.0_60]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.7.0_60]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [rt.jar:1.7.0_60]
    at java.lang.Class.newInstance(Class.java:374) [rt.jar:1.7.0_60]
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:373) [rt.jar:1.7.0_60]

Maybe there is something wrong with my dependencies? To I have to configure the EAP in a special way?

Please provide a small example app with proper configured pom.xml.

Thx

**Comment by fcorneli** [comment]
Are you sure you followed all steps as described in the README-batch.txt within the ZIP?

**Comment by tokad** [comment]
Thx a lot for the tip. I only read the readme on github and browsed through the modules here. Now it works. You are great :-). Sorry for raising an issue here.
