### ISSUE TITLE
 Ensure the deployment has a META-INF/batch.xml file or the META-INF/batch-jobs directory contains batch configuration files

### ISSUE THREAD

**Issue by bflorat** [fcorneli/jberet-eap6#3]
Hi,
- Jboss eap 6.3
- eap6-batch-dist-1.0.2.zip (and i followed all README-batchs.txt instructions about setting modules)
- I have an ear with an EJB jar that contains a JSL file in its META-INF/batch-jobs/job.xml

I get this error (seems like jberet can't load the JSL files)

Any idea ?

```
00:07:10,895 ERROR [org.quartz.core.ErrorLogger] (GedBatchCollecterAtlasScheduler_QuartzSchedulerThread) An error occured instantiating job to be executed. job= 'GED_BATCH_COLLECTERATLAS.TacheCollecterAtlas': org.quartz.SchedulerException: Problem instantiating class '***.Tache' [See nested exception: org.jboss.weld.exceptions.WeldException: WELD-000049 Unable to invoke [method] @PostConstruct public ****.postConstruct() on ****@328f6e60]
    at ****.javaee6.batch.quartz.CdiJobFactory.newJob(CdiJobFactory.java:41) [general-javaee6-batch-1.0.1-0.jar:1.0.1-0]
    at org.quartz.core.JobRunShell.initialize(JobRunShell.java:140) [quartz-1.8.6.jar:]
    at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:364) [quartz-1.8.6.jar:]
Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049 Unable to invoke [method] @PostConstruct public ****.postConstruct() on ****@328f6e60
    at org.jboss.weld.bean.AbstractClassBean.defaultPostConstruct(AbstractClassBean.java:405) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget.postConstruct(ManagedBean.java:178) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:298) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:68) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:626) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:692) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:136) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:796) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:805) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget$1$1.proceed(ManagedBean.java:165) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget$1.work(ManagedBean.java:161) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$FixInjectionPoint.run(ManagedBean.java:135) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean$ManagedBeanInjectionTarget.inject(ManagedBean.java:157) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:297) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:68) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:626) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:653) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at ****.javaee6.batch.quartz.CdiJobFactory.getBean(CdiJobFactory.java:48) [general-javaee6-batch-1.0.1-0.jar:1.0.1-0]
    at ****.javaee6.batch.quartz.CdiJobFactory.newJob(CdiJobFactory.java:39) [general-javaee6-batch-1.0.1-0.jar:1.0.1-0]
    ... 2 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_80]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_80]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_80]
    at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_80]
    at org.jboss.weld.util.reflection.SecureReflections$13.work(SecureReflections.java:267) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:52) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInvocation(SecureReflectionAccess.java:137) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.util.reflection.SecureReflections.invoke(SecureReflections.java:263) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.introspector.jlr.WeldMethodImpl.invoke(WeldMethodImpl.java:168) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    at org.jboss.weld.bean.AbstractClassBean.defaultPostConstruct(AbstractClassBean.java:403) [weld-core-1.1.23.Final-redhat-1.jar:1.1.23.Final-redhat-1]
    ... 21 more
Caused by: java.util.ServiceConfigurationError: javax.batch.operations.JobOperator: Provider org.jberet.operations.JobOperatorImpl could not be instantiated
    at java.util.ServiceLoader.fail(ServiceLoader.java:224) [rt.jar:1.7.0_80]
    at java.util.ServiceLoader.access$100(ServiceLoader.java:181) [rt.jar:1.7.0_80]
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:377) [rt.jar:1.7.0_80]
    at java.util.ServiceLoader$1.next(ServiceLoader.java:445) [rt.jar:1.7.0_80]
    at javax.batch.runtime.BatchRuntime.getJobOperator(BatchRuntime.java:57) [jboss-batch-api_1.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at ****.postConstruct(SMCollecterAtlas.java:30) [ged-servicemetier-collecteratlas-1.0.0-0-SNAPSHOT.jar:1.0.0-0-SNAPSHOT]
    ... 31 more
Caused by: java.lang.IllegalStateException: WFLYBAT000001: BeanManager service was not added on the deployment. Ensure the deployment has a META-INF/batch.xml file or the META-INF/batch-jobs directory contains batch configuration files.
    at org.wildfly.jberet.services.BatchEnvironmentService$WildFlyBatchEnvironment.getArtifactFactory(BatchEnvironmentService.java:123) [eap6-jberet-1.0.2.jar:1.0.2]
    at org.wildfly.jberet.DelegatingBatchEnvironment.getArtifactFactory(DelegatingBatchEnvironment.java:52) [eap6-jberet-1.0.2.jar:1.0.2]
    at org.jberet.operations.JobOperatorImpl.<init>(JobOperatorImpl.java:89) [jberet-core-1.1.0.Alpha3.r2.jar:1.1.0.Alpha3.r2]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_80]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [rt.jar:1.7.0_80]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.7.0_80]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [rt.jar:1.7.0_80]
    at java.lang.Class.newInstance(Class.java:383) [rt.jar:1.7.0_80]
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:373) [rt.jar:1.7.0_80]
    ... 34 more
```

**Comment by bflorat** [comment]
It works now. The problem was that I called the `BatchRuntime.getJobOperator()` from a quartz job and it causes classloader issues. No problem when calling it from a regular stateless bean.
